// config.js
const CONFIG = {
    enemySpawnTimer: null,
    lastEnemySpawnTime : 0, // 
    canvas: document.getElementById('gameCanvas'),
    ctx: document.getElementById('gameCanvas').getContext('2d'),
    player: {
      x: 0,
      y: 0,
      width: 80,
      height: 80,
      speed: 10,
      image: new Image(),
    },
    bullets: [],
    specialBulletsLeft: 10,
    enemies: [],
    backgroundImage: new Image(),
    backgroundStars: [],
    keys:{},
    gameOverOverlay: null,
    pauseOverlay: null,
    score: 0,
    life: 5,
    difficulty: 'medium',
    highScores: JSON.parse(localStorage.getItem('highScores')) || [0, 0, 0],
    isPaused: false,
    enemySpeedMultiplier: 1.2,
    maxEnemySpeedMultiplier: 3,
    enemySpawnInterval: 1000,
    minEnemySpawnInterval: 300,
    bulletSound:new Audio('music/bullet.mp3'),
    explosionSound: new Audio('music/explosion_sound.mp3'),
    // bgMusic: new Audio('music/bgmusic_temp_cut.mp3'),
    //homepageMusic: new Audio('music/homepage_music.mp3'),
    lastaccelerate_score: 0,
    isGameRunning: false,
    lastrecover_time: 0,
    homepageMusicList: [
      new Audio('music/homepage_music.mp3'),
      new Audio('music/night.mp3'),
      new Audio('music/monster.mp3'),
    ],
    bgMusicList: [
      new Audio('music/bgmusic_new.mp3'),
      new Audio('music/bgmusic_mini.mp3'),
      new Audio('music/bgmusic_temp_cut.mp3'),
    ],
    homepageMusic: null,
    bgMusic: null,
    bgMusicIndex: null,
    homepageMusicIndex: null,
  };
  