// config.js
const CONFIG = {
    canvas: document.getElementById('gameCanvas'),
    ctx: document.getElementById('gameCanvas').getContext('2d'),
    player: {
      x: 0,
      y: 0,
      width: 80,
      height: 80,
      speed: 15,
      image: new Image(),
    },
    bullets: [],
    specialBulletsLeft: 10,
    enemies: [],
    backgroundImage: new Image(),
    backgroundStars: [],
    keys:{},
    gameOverOverlay: null,
    pauseOverlay: null,
    score: 0,
    life: 3,
    difficulty: 'medium',
    highScores: JSON.parse(localStorage.getItem('highScores')) || [0, 0, 0],
    isPaused: false,
    enemySpeedMultiplier: 1.2,
    maxEnemySpeedMultiplier: 3,
    enemySpawnInterval: 1000,
    minEnemySpawnInterval: 300,
    bulletSound:new Audio('music/bullet.mp3'),
    explosionSound: new Audio('music/explosion_sound.mp3'),
    bgMusic: new Audio('music/bgmusic_temp.mp3'),
    homepageMusic: new Audio('music/homepage_music.mp3'),
    lastaccelerate_score: 0,
    isGameRunning: false,
  };
  